# File: .github/workflows/academic-version.yml

name: Build LaTeX Document

on:
  push:
    branches: [ academic ]
  pull_request:
    branches: [ academic ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexmk

    - name: Compile LaTeX to PDF
      run: |
        latexmk -pdf -interaction=nonstopmode -file-line-error main.tex

    - name: Rename PDF to elewah_resume.pdf
      run: |
        mv main.pdf elewah_resume.pdf

    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: elewah-resume
        path: elewah_resume.pdf

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add elewah_resume.pdf
        git commit -m "Auto-update generated file [skip ci]" || echo "Nothing to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
