# File: .github/workflows/latex.yml

name: Build LaTeX Document

on:
  push:
    branches: [ network ]
  pull_request:
    branches: [ network ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexmk

    - name: Compile LaTeX to PDF
      run: |
        latexmk -pdf -interaction=nonstopmode -file-line-error main.tex

    - name: Rename PDF to elewah_resume.pdf
      run: |
        mv main.pdf elewah_resume.pdf

    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: elewah-resume
        path: elewah_resume.pdf
