# File: .github/workflows/latex.yml

name: Build LaTeX Document

on:
  push:
    branches: [ main ]  # or 'master' if that's your default branch
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up LaTeX environment
      uses: teatimeguest/setup-texlive-action@v2
      with:
        packages: >-
          latexmk
          texlive-latex-recommended
          texlive-latex-extra
          texlive-fonts-recommended
          texlive-science
          texlive-bibtex-extra
          texlive-lang-english

    - name: Compile LaTeX to PDF
      run: |
        latexmk -pdf -interaction=nonstopmode -file-line-error main.tex

    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: main-pdf
        path: main.pdf
